server:
  port: 8004
debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7910/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ppx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zaq1xsw2@mysql
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 80
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
    useGlobalDataSourceStat: true
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.show.comm.mybatis
  configLocation: classpath:mybatis.xml